# Server
server.port=8081

# Disable MongoDB auto configuration
spring.autoconfigure.exclude=\
org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration,\
org.springframework.boot.data.mongodb.autoconfigure.DataMongoAutoConfiguration,\
org.springframework.boot.data.mongodb.autoconfigure.DataMongoRepositoriesAutoConfiguration

# Disable ActiveMQ / JMS
spring.jms.listener.auto-startup=false

# Disable Eureka
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Queue property
app.messaging.trainer-workload-queue=trainer.workload.queue