# Server
server.port=8081

# MongoDB - Docker network service name
spring.mongodb.uri=mongodb://mongodb:27017/trainer_workload_db
spring.mongodb.database=trainer_workload_db
spring.data.mongodb.auto-index-creation=true

# Eureka - Docker network service name
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

# ActiveMQ - Docker network service name
spring.activemq.broker-url=tcp://activemq:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.listener.auto-startup=true

# Queue
app.messaging.trainer-workload-queue=trainer.workload.queue