# Server
server.port=8081

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=trainer_workload_db

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

# ActiveMQ
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL}
spring.activemq.user=${ACTIVEMQ_USER}
spring.activemq.password=${ACTIVEMQ_PASSWORD}

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n